export function memoryWidget(origin: string) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
  *{box-sizing:border-box}body{font-family:system-ui,sans-serif;margin:0;background:#f5f7f9;color:#1c3447;padding:24px;font-size:15px}h1{font-size:25px;margin:0 0 6px;letter-spacing:-.04em}p{color:#647d8c;line-height:1.65}button,select{font:inherit;border:1px solid #c6d9df;border-radius:7px;background:white;color:#254759;padding:10px 13px;cursor:pointer}button:disabled{opacity:.5;cursor:default}.header{display:flex;justify-content:space-between;gap:20px;align-items:center;flex-wrap:wrap}.notice{font-size:13px;background:#e8f3ee;color:#326c59;border-radius:8px;padding:13px 16px;margin:22px 0}.row{padding:18px;background:#fff;border:1px solid #dce6eb;border-radius:9px;margin:12px 0}.title{font-weight:600;text-align:left;background:transparent;border:0;padding:0}.status{display:inline-block;margin-left:12px;font-size:12px;background:#eef3f5;padding:5px 8px;border-radius:5px}.record{padding-top:12px;border-top:1px solid #e1e9ed;margin-top:14px}.error{color:#a43d37}.scope{font-size:13px;color:#657d88}pre{font-size:12px;white-space:pre-wrap;word-break:break-word}.actions{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.footer{font-size:12px;margin-top:24px;color:#7b919e}
  </style></head><body><div class="header"><div><h1>Research Kernel</h1><p style="margin:0">Persistent scientific memory</p></div><button id="web">Open full workbench ↗</button></div>
  <div class="notice">Verification is scoped. A bounded pass checks the exact recipe and finite grid. External evidence remains unverified.</div>
  <div class="actions"><select id="workspaces" aria-label="Research workspace"><option value="">Choose a workspace</option></select><button id="refresh">Refresh</button></div>
  <p id="error" class="error" role="alert"></p><main id="claims"><p>Connecting to your research memory…</p></main><p class="footer">Private workspaces · Immutable revisions · Non-transferable contribution records</p>
  <script>
  const siteOrigin = __SITE_ORIGIN__;
  const pending = new Map(); let nextId = 1; let workspaceId = null; let memory = null;
  const err = document.getElementById('error'), root = document.getElementById('claims'), select = document.getElementById('workspaces');
  function request(method, params) { return new Promise((resolve,reject) => { const id=nextId++; const timer=setTimeout(()=>{pending.delete(id);reject(new Error('The host did not respond. Try refreshing.'));},20000); pending.set(id,{resolve,reject,timer}); window.parent.postMessage({jsonrpc:'2.0',id,method,params},'*'); }); }
  function notify(method,params){ window.parent.postMessage({jsonrpc:'2.0',method,params},'*'); }
  function showError(e){err.textContent=e.message||String(e);}
  async function tool(name,args){ const r=await request('tools/call',{name,arguments:args}); if(r.isError)throw new Error(r.content?.[0]?.text||'Research request failed.');return r.structuredContent; }
  function elem(tag,text,cls){const e=document.createElement(tag); if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
  function renderMemory(v){memory=v;root.replaceChildren(); if(!v.claims.length){root.append(elem('p','This workspace has no claims. Use the full workbench or ask ChatGPT to record one.'));return;}
    for(const c of v.claims){const r=c.revisions[c.revisions.length-1], row=elem('section',undefined,'row'), title=elem('button',r.title,'title'), status=elem('span',c.status,'status'); row.append(title,status);
      const panel=elem('div',undefined,'record');panel.hidden=true;title.onclick=()=>{panel.hidden=!panel.hidden;notify('ui/update-model-context',{structuredContent:{workspaceId,claimId:c.id,revisionHash:r.hash}});};
      panel.append(elem('p',r.statement),elem('p','Assumptions: '+(r.assumptions||'None stated'),'scope'),elem('p','Scope: '+r.scope,'scope'));
      if(r.recipe){const b=elem('button','Run bounded check');b.disabled=c.needsReview;b.onclick=async()=>{b.disabled=true;err.textContent='';try{await tool('rk_check',{workspaceId,expectedRevision:memory.revision,requestId:crypto.randomUUID(),claimId:c.id,expectedHash:r.hash});await loadMemory();}catch(e){showError(e);}finally{b.disabled=c.needsReview;}};panel.append(b);}
      for(const receipt of c.receipts.filter(t=>t.claimRevision===r.hash)){panel.append(elem('p',receipt.result.outcome+' · '+receipt.result.cases+'/'+receipt.result.totalCases+' cases','scope'));if(receipt.result.counterexample)panel.append(elem('pre',JSON.stringify(receipt.result.counterexample,null,2)));if(receipt.result.error)panel.append(elem('p',receipt.result.error,'error'));}
      panel.append(elem('p','Revision '+r.number+' · '+r.hash.slice(0,16)+'…','scope'));row.append(panel);root.append(row);
    }notify('ui/notifications/size-changed',{height:document.documentElement.scrollHeight}); }
  async function loadMemory(){if(!workspaceId)return;err.textContent='';const v=await tool('rk_memory_get',{workspaceId});renderMemory(v);}
  function renderWorkspaces(v){select.replaceChildren(elem('option','Choose a workspace')); select.firstChild.value='';for(const w of v.workspaces){const o=elem('option',w.name+(w.role==='invited'?' · invitation pending':''));o.value=w.id;o.disabled=w.role==='invited';select.append(o);}if(!workspaceId)workspaceId=v.workspaces.find(w=>w.role!=='invited')?.id||null;if(workspaceId){select.value=workspaceId;loadMemory().catch(showError);}else root.replaceChildren(elem('p','Create your first private workspace in the full workbench, or ask ChatGPT to create it.'));}
  window.addEventListener('message',e=>{if(e.source!==window.parent)return;const m=e.data;if(!m||m.jsonrpc!=='2.0')return;if(m.id!==undefined&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);return;}if(m.method==='ui/notifications/tool-result'&&m.params?.structuredContent?.workspaces)renderWorkspaces(m.params.structuredContent);});
  select.onchange=()=>{workspaceId=select.value||null;loadMemory().catch(showError);};document.getElementById('refresh').onclick=()=>tool('rk_workspaces_list',{}).then(renderWorkspaces).catch(showError);
  document.getElementById('web').onclick=()=>request('ui/open-link',{url:siteOrigin+'/'}).catch(showError);
  request('ui/initialize',{protocolVersion:'2026-01-26',appInfo:{name:'Research Kernel',version:'0.2.0'},appCapabilities:{}}).then(()=>{notify('ui/notifications/initialized',{});return tool('rk_workspaces_list',{});}).then(renderWorkspaces).catch(showError);
  </script></body></html>`.replace("__SITE_ORIGIN__", JSON.stringify(origin).replace(/</g, "\\u003c"));
}
